import localFont from "next/font/local";
import "./globals.css";
import Sidebar from './components/Sidebar'; // You may rename it to Sidebar.js to keep naming intuitive.

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body>
      <div style={{ display: 'flex', height: '100vh' }}>
        <Sidebar />
        <div style={{ flex: 1 }}>
          <main style={{ padding: '20px' }}>
            {children}
          </main>
        </div>
      </div>
    </body>
  </html>
  );
}
